baseURL = "https://kapoko.github.io/delicious-hamburgers/"
languageCode = "en-us"
title = "Delicious Hamburgers ğŸ”"
staticDir = ["static", "dist"]

[params]
    author = "Kasper Koman"
    description = "Beautiful hamburger menu buttons"